# Generated by Django 2.2.2 on 2019-07-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Time of last message')),
                ('message_1', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 1')),
                ('message_2', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 2')),
                ('message_3', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 3')),
                ('message_4', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 4')),
                ('message_5', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 5')),
                ('message_6', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 6')),
                ('message_7', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 7')),
                ('message_8', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 8')),
                ('message_9', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 9')),
                ('message_10', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Message 10')),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
