# Generated by Django 2.2.2 on 2019-07-06 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190706_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 7, 6), null=True, verbose_name='Time of latest message'),
        ),
    ]
