# Generated by Django 2.2.2 on 2019-07-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190706_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='author',
        ),
        migrations.AddField(
            model_name='messages',
            name='author_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 1'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_10',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 10'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 2'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 3'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 4'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 5'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 6'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 7'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 8'),
        ),
        migrations.AddField(
            model_name='messages',
            name='author_9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author 9'),
        ),
    ]
