# Generated by Django 2.2.3 on 2019-07-20 11:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField(default=catalog.models.current_date, null=True, verbose_name='Date')),
                ('c_time', models.CharField(default=catalog.models.current_time, max_length=100, null=True, verbose_name='Time (24 hr.)')),
                ('c_coordinator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Pool Coordinator')),
                ('c_main_doors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Doors')),
                ('c_south_patio_doors', models.CharField(blank=True, max_length=100, null=True, verbose_name='South Patio Doors')),
                ('c_north_patio_doors_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='North Patio Doors 1')),
                ('c_north_patio_doors_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='North Patio Doors 2')),
                ('c_monitor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Monitor')),
                ('c_directors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient/Visitor Director(s)')),
                ('c_runners', models.CharField(blank=True, max_length=100, null=True, verbose_name='Command Centre Runner(s)')),
                ('c_num_staff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Staff Present')),
                ('c_explain', models.NullBooleanField(verbose_name='Explained to Participants')),
            ],
            options={
                'verbose_name': 'Cafeteria',
                'verbose_name_plural': 'Cafeteria',
            },
        ),
        migrations.CreateModel(
            name='CodeBlue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_date', models.DateField(default=catalog.models.current_date, verbose_name='Date')),
                ('blue_time', models.CharField(default=catalog.models.current_time, max_length=100, verbose_name='Time (24hr.)')),
                ('blue_what_went_well', models.TextField(blank=True, null=True, verbose_name='What Went Well')),
                ('blue_did_not_go_well', models.TextField(blank=True, null=True, verbose_name="What Didn't Go Well")),
                ('blue_system_issues', models.TextField(blank=True, null=True, verbose_name='System Issues')),
                ('blue_what_was_learned', models.TextField(blank=True, null=True, verbose_name='What Was Learned/Recommendations/Goals')),
                ('blue_who_will_follow_up', models.TextField(blank=True, null=True, verbose_name='Who Will Follow Up/Communicate')),
            ],
            options={
                'verbose_name': 'Code Blue',
                'verbose_name_plural': 'Code Blue',
            },
        ),
        migrations.CreateModel(
            name='CodePink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pink_date', models.DateField(default=catalog.models.current_date, verbose_name='Date')),
                ('pink_time', models.CharField(default=catalog.models.current_time, max_length=100, verbose_name='Time (24hr.)')),
                ('pink_what_went_well', models.TextField(blank=True, null=True, verbose_name='What Went Well')),
                ('pink_did_not_go_well', models.TextField(blank=True, null=True, verbose_name="What Didn't Go Well")),
                ('pink_system_issues', models.TextField(blank=True, null=True, verbose_name='System Issues')),
                ('pink_what_was_learned', models.TextField(blank=True, null=True, verbose_name='What Was Learned/Recommendations/Goals')),
                ('pink_who_will_follow_up', models.TextField(blank=True, null=True, verbose_name='Who Will Follow Up/Communicate')),
            ],
            options={
                'verbose_name': 'Code Pink',
                'verbose_name_plural': 'Code Pink',
            },
        ),
        migrations.CreateModel(
            name='CodeStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Time of Status Change')),
                ('code_red_status', models.CharField(blank=True, default='Normal', max_length=100, null=True, verbose_name='Code Red Status')),
                ('status_setter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Setter')),
                ('from_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='From')),
                ('to_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='To')),
            ],
            options={
                'verbose_name': 'Code Red Status',
                'verbose_name_plural': 'Code Red Status',
            },
        ),
        migrations.CreateModel(
            name='East_Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateField(blank=True, default=catalog.models.current_date, null=True, verbose_name='Date')),
                ('e_time', models.CharField(default=catalog.models.current_time, max_length=100, null=True, verbose_name='Time (24 hr.)')),
                ('e_coordinator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Pool Coordinator')),
                ('e_main_doors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Doors')),
                ('e_lab_entrance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lab Entrance')),
                ('e_ed_entrance', models.CharField(blank=True, max_length=100, null=True, verbose_name='ED Entrance')),
                ('e_monitor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Monitor')),
                ('e_directors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient/Visitor Director(s)')),
                ('e_runners', models.CharField(blank=True, max_length=100, null=True, verbose_name='Command Centre Runner(s)')),
                ('e_num_staff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Staff Present')),
                ('e_explain', models.NullBooleanField(verbose_name='Explained to Participants')),
            ],
            options={
                'verbose_name': 'East Lobby',
                'verbose_name_plural': 'East Lobby',
            },
        ),
        migrations.CreateModel(
            name='IncidentCommander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_date', models.DateField(blank=True, default=catalog.models.current_date, null=True, verbose_name='Date')),
                ('i_time', models.CharField(default=catalog.models.current_time, max_length=100, null=True, verbose_name='Time (24 hr.)')),
                ('i_commander', models.CharField(blank=True, max_length=100, null=True, verbose_name='Incident Commander')),
                ('i_num_staff_c', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Staff at Cafeteria')),
                ('i_num_staff_e', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Staff at East Lobby')),
                ('i_num_staff_t', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Staff at Town Centre')),
                ('i_captain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area Captain')),
                ('i_signal_silence_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time (24 hr.) of Signal Silence')),
                ('i_all_clear_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time (24 hr.) of All Clear')),
                ('i_location_of_evacuation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location of Evacuation')),
                ('i_area_of_refuge', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area of Refuge')),
                ('i_signed_fire_documentation', models.NullBooleanField(verbose_name='Signed Fire Department Documentation')),
            ],
            options={
                'verbose_name': 'Incident Command',
                'verbose_name_plural': 'Incident Command',
            },
        ),
        migrations.CreateModel(
            name='Town_Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_date', models.DateField(blank=True, default=catalog.models.current_date, null=True, verbose_name='Date')),
                ('t_time', models.CharField(default=catalog.models.current_time, max_length=100, null=True, verbose_name='Time (24 hr.)')),
                ('t_coordinator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Pool Coordinator')),
                ('t_horticultural', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horticultural Entrance')),
                ('t_town_centre_main_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Town Centre/Main Street')),
                ('t_monitor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone Monitor')),
                ('t_directors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patient/Visitor Director(s)')),
                ('t_runners', models.CharField(blank=True, max_length=100, null=True, verbose_name='Command Centre Runner(s)')),
                ('t_num_staff', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Staff Present')),
                ('t_explain', models.NullBooleanField(verbose_name='Explained to Participants')),
            ],
            options={
                'verbose_name': 'Town Centre',
                'verbose_name_plural': 'Town Centre',
            },
        ),
    ]
