# Generated by Django 2.2.3 on 2019-07-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeblue',
            old_name='blue_did_not_go_well',
            new_name='blue_what_did_not_go_well',
        ),
        migrations.RenameField(
            model_name='codepink',
            old_name='pink_did_not_go_well',
            new_name='pink_what_did_not_go_well',
        ),
    ]
