# Generated by Django 2.2.3 on 2019-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190720_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='c_mock',
            field=models.NullBooleanField(verbose_name='Mock'),
        ),
        migrations.AddField(
            model_name='codeblue',
            name='blue_mock',
            field=models.NullBooleanField(verbose_name='Mock'),
        ),
        migrations.AddField(
            model_name='codepink',
            name='pink_mock',
            field=models.NullBooleanField(verbose_name='Mock'),
        ),
        migrations.AddField(
            model_name='east_lobby',
            name='e_mock',
            field=models.NullBooleanField(verbose_name='Mock'),
        ),
        migrations.AddField(
            model_name='incidentcommander',
            name='i_mock',
            field=models.NullBooleanField(verbose_name='Mock'),
        ),
        migrations.AddField(
            model_name='town_centre',
            name='t_mock',
            field=models.NullBooleanField(verbose_name='Mock'),
        ),
    ]
